create table dbo.cltClients
(
    cltId                        int identity,
    Stamp                        datetime not null,
    ClientNumber                 decimal(10) not null,
    ClientName                   varchar(255) not null,
    MesgResps                    ntext not null,
    msgScriptId                  int,
    MaxSchedCalls                int,
    ScreenLayout                 ntext not null,
    subId                        int,
    viewId                       int,
    searchId                     int,
    SaveDiscardedMessages        bit not null,
    MsgPurgeTime                 int,
    CheckinPending               bit not null,
    SandboxSearch                ntext,
    Url                          nvarchar(1000) not null,
    TimezoneOffset               bigint not null,
    ocschedID                    int,
    FilterRoledefIDs             ntext,
    LogVoice                     bit not null,
    PerfectAnswer                bit not null,
    msgScriptIDWeb               int,
    msgScriptIDWebMessaging      int,
    BillingCode                  nvarchar(150) not null,
    DefaultBehaviorType          int not null,
    DefaultBehaviorParameter     ntext,
    AutoConnect                  bit not null,
    Emergency                    bit not null,
    DoneKeyCancelsScript         bit not null,
    msgScriptIDMergeComm         int,
    HangupRemovesWorkArea        bit not null,
    TransferConfRemovesWorkArea  bit not null,
    PciCompliance                bit not null,
    ReassignTime                 int,
    DefaultRoute                 int,
    MusicOnHold                  int,
    OverrideOpLimit              bit not null,
    MusicOnHoldAfterAutoAnswer   int,
    AutoAnswerRings              int,
    AnnounceATTA                 bit not null,
    RepeatATTA                   bit not null,
    AnnounceCallsInQue           bit not null,
    CallerIdNumber               nvarchar(20),
    CallerIdName                 nvarchar(100),
    ViewMessagesDefaultFilterOld nvarchar(500),
    Skill                        int not null,
    DontStartScriptOnFetch       bit not null,
    ScreenCapture                bit not null,
    MaxCallsFromDispatchJobs     int not null,
    SelectNextUndelMsgWhenDel    bit not null,
    playQualityPrompt            bit not null,
    loggerBeep                   bit not null,
    LoggerBeepInterval           int not null,
    AutoAnswerInterval           int not null,
    specialOldToNew              bit not null,
    saveEditedSpecial            bit not null,
    showSpecials                 bit not null,
    showInfos                    bit not null,
    ViewMessagesDefaultFilter    nvarchar(max),
    CheckinPasscode              nvarchar(100),
    DirectCheckin                bit not null,
    DefaultCOS                   int not null,
    VoiceMailMaxLength           int not null,
    VoiceMailPlayBeep            bit not null,
    VoiceMailOldToNew            bit not null,
    VoiceMailAnnounce            int not null,
    VoiceMailRevert              bit not null,
    VmChgPasscode                bit not null,
    VmChgGreeting                bit not null,
    VoiceMailPrivate             bit not null,
    VoiceMailAni                 bit not null,
    SecureVMTransfer             bit not null,
    NewVmRunsMergecomm           bit not null,
    ExcludeFromSurvey            bit not null,
    VoiceMailMenu                int not null,
    VoiceMailGreetOptions        int not null,
    AnswerPhrase                 nvarchar(2000) not null,
    LogWhenMessageViewed         bit not null,
    msgScriptIdAcd               int,
    DIDLimit                     int not null,
    UseOrgClientForDIDLimit      bit not null,
    AniSources                   nvarchar(max),
    AniBehavior                  nvarchar(max),
    ExemptFromSystemHoliday      bit not null,
    RecordPatch                  bit not null
);

create table dbo.cltInfo
(
    infoId  int identity,
    Stamp   datetime not null,
    cltId   int not null,
    OrderId int not null,
    [Index] text,
    Info    text
);

create table dbo.dirListingFields
(
    id                       int identity,
    listId                   int,
    subfieldId               int,
    subId                    int,
    cltfieldID               int,
    cltID                    int,
    Field                    nvarchar(400) not null,
    DataType                 int not null,
    imageId                  int,
    contactEmailId           int,
    contactPhoneId           int,
    contactTapPagerId        int,
    contactSmsId             int,
    searchField              nvarchar(400),
    contactSecureMessagingId int,
    contactSnppId            int,
    contactWctpId            int,
    contactFaxId             int,
    contactVoceraId          int,
    contactCiscoId           int,
    Url                      nvarchar(400)
);